### PR TITLE
Use conftest.py to share fixtures among tests,

### PR DESCRIPTION
**Pull request by kollivier**
...and begin removing duplicated fixtures from tests. 

As we start adding more tests, being able to keep test files reasonably small and readable will be important, as will avoiding duplication of test data. Anything we can do to decrease the pain of grokking or writing tests helps to ensure more tests get written!

### CODE REVIEW

**Comment by ivanistheone** [comment]
Good job on the test cleanup Kevin. I rebased this PR to avoid the merge conflict then added a small fix to make tests pass.

Good to merge now --- I'll let you click that green button ;)

**Comment by ivanistheone** [comment]
screen shot 2018-06-26 at 3 30 28 pm

**Comment by kollivier** [comment]
GitHub won't let me click the green button since I don't seem to have write access to this repo. ;-)

**Comment by jayoshih** [comment]
@kollivier Added you as an admin!

**Pull request merged**
